rvDjango/project7/app7/urls.py
from django.urls import path
from .import views
app_name='app7'
urlpatterns=[
    path('hello',views.hello,name='hello'),
    path('',views.index,name='index'),
    path('register',views.register,name='register'),
]

rvDjango/project7/project7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app7.urls')),
]

rvDjango/project7/app7/models.py
from django.db import models
# Create your models here.
class Table2(models.Model):
    Name=models.CharField(max_length=20)
    Age=models.IntegerField()
    Marks=models.IntegerField()
class Table1(models.Model):
    Name=models.CharField(max_length=20)
    Age=models.IntegerField()
    Place=models.CharField(max_length=20)
    Email=models.EmailField()
    Password=models.CharField(max_length=20)

rvDjango/project7/app7/forms.py
from django import forms
from .models import Table1
class RegisterForm(forms.ModelForm):
    class Meta():
        model=Table1
        fields='__all__'

rvDjango/project7/app7/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from.forms import RegisterForm
from django.contrib import messages
# Create your views here.
def hello(request):
    return HttpResponse('welcome to Django')
def index(request):
    return render(request,'index.html')
def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Data saved")
            return redirect('/')
    else:
        form=RegisterForm()
    return render(request,'register.html',{'form':form})    

rvDjango/project7/app7/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            My WebPage
        </title>
    </head>
    <body>
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        <br>
        I am Rejeth Vinod<br>
        Kannur<br>
        {{datas}}

        <a href="{% url 'app7:register' %}">Register</a>
    </body>
</html>

rvDjango/project7/app7/templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            My Table2
        </title>
    </head>
    <body>
        This is register table<br>
        <form action="" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    {{form.as_table}}
                </tr>
            </table>
            <input type="submit" name="btsub" value="Register">
        </form>
    </body>
</html>