rvDjango/project9/app9/urls.py
from django.urls import path,include
from.import views
app_name='app9'
urlpatterns=[
    path('hello',views.hello ,name='hello'),
    path('',views.index,name='index'),
    path('register',views.register,name='register'),
    path('login/', views.login, name="login"),
    path('home/<int:id>', views.home, name="home"),
]

rvDjango/project9/project9/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app9.urls'))
]

rvDjango/project9/app9/models.py
from django.db import models
# Create your models here.
class Register(models.Model):
    Name=models.CharField(max_length=20)
    Age=models.IntegerField()
    Place=models.CharField(max_length=20)
    Email=models.EmailField()
    Password=models.CharField(max_length=8)

rvDjango/project9/app9/forms.py
from django import forms
from .models import Register
class RegisterForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput, max_length=8,min_length=3)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput, max_length=8, min_length=3)
    class Meta():
        model=Register
        fields='__all__'
class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput, max_length=8,min_length=3)
    class Meta():
        model=Register
        fields=('Email','Password')

rvDjango/project9/app9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegisterForm, LoginForm
from .models import Register
from django.contrib import messages
# Create your views here.
def hello(request):
    return HttpResponse("Welcome to Django")
def index(request):
    name='Register Counter'
    return render(request,'index.html',{'datas':name})
def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            place=form.cleaned_data['Place']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['ConfirmPassword']
            user=Register.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,"Mail already exists")
                return redirect('/register')
            elif password!=confirmpassword:
                messages.warning(request,"Password already exists")
                return redirect('/register')
            else:
                tab=Register(Name=name, Age=age, Place=place, Email=email, Password=password)
                tab.save()
                messages.success(request,"Data Saved")
                return redirect('/')
    else: 
        form=RegisterForm()
    return render(request,'register.html',{'form':form})

def login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']

            try:
                user=Register.objects.get(Email=email)
                if not user:
                    messages.warning(request,"Mail does not exist")
                    return redirect('/login')
                elif password!=user.Password:
                    messages.warning(request,"Password vdoes not match")
                    return redirect('/login')
                else:
                    messages.success(request,"Login success")
                    return redirect('/home/%s' % user.id )
            except:
                messages.warning(request,"email or password incorrect")
                return redirect('/login')

    else: 
        form=LoginForm()
    return render(request,'login.html',{'form':form})
def home(request,id):
    user=Register.objects.get(id=id)
    return render(request,'home.html',{'user':user})

rvDjango/project9/app9/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    welcome {{user.Name}}
</body>
</html>

rvDjango/project9/app9/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Secure Register
        </title>
    </head>
    <body>
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        <br>
        Please click the Highlighted Text<br>
        {{datas}}

        <a href="{% url 'app9:register' %}">Register</a>
        <a href="{% url 'app9:login' %}">Login</a>
    </body>
</html>

rvDjango/project9/app9/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Document
        </title>
    <body>
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        <form action="" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    {{form.as_table}}
                </tr>
            </table>
            <input type="submit" value="Login">
        </form>
    </body>
    </head>
</html>

rvDjango/project9/app9/templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            My Table
        </title>
    </head>
    <body>
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        This is Register Table<br>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    {{form.as_table}}
                </tr>
            </table>
            <input type="submit" name="btsub" value="Register">
        </form>
    </body>
</html>