rvDjango/project8/app8/urls.py
from django.urls import path,include
from .import views
app_name='app8'
urlpatterns=[
    path('hello',views.hello,name='hello'),
    path('',views.index,name='index'),
    path('register',views.register,name='register'),
    path('login/', views.login, name="login"),
    path('home/<int:id>', views.home, name="home"),
    path('mail',views.mail,name='mail'),
]

rvDjango/project8/project8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app8.urls')),
]

rvDjango/project8/app8/models.py
from django.db import models
# Create your models here.
class Table1(models.Model):
    Name=models.CharField(max_length=20)
    Age=models.IntegerField()
    Place=models.CharField(max_length=20)
    Email=models.EmailField()
    Password=models.CharField(max_length=20)

rvDjango/project8/app8/forms.py
from django import forms
from .models import Table1
class RegisterForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=3)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=3)
    class Meta():
        model=Table1
        fields='__all__'
class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput, max_length=8,min_length=3)
    class Meta():
        model=Table1
        fields=('Email','Password')

rvDjango/project8/app8/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import RegisterForm, LoginForm
from.models import Table1
from project8 import settings
from django.core.mail import send_mail
from django.contrib import messages
# Create your views here.
def hello(request):
    return HttpResponse("Welcome to Django")
def index (request):
    name='Register counter'
    return render(request,'index.html',{'datas':name})
def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            place=form.cleaned_data['Place']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['ConfirmPassword']
            user=Table1.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,"Mail already exists")
                return redirect('/register')
            elif password!=confirmpassword:
                messages.warning(request,"Password already exists")
                return redirect('/register')
            else:
                tab=Table1(Name=name,Age=age,Place=place,Email=email,Password=password)
                tab.save()
                messages.success(request,"Data Saved")
                return redirect('/')
    else:
        form=RegisterForm()
    return render(request,'register.html',{'form':form})
def login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']

            try:
                user=Table1.objects.get(Email=email)
                if not user:
                    messages.warning(request,"Mail does not exist")
                    return redirect('/login')
                elif password!=user.Password:
                    messages.warning(request,"Password vdoes not match")
                    return redirect('/login')
                else:
                    messages.success(request,"Login success")
                    return redirect('/home/%s' % user.id )
            except:
                messages.warning(request,"email or password incorrect")
                return redirect('/login')

    else: 
        form=LoginForm()
    return render(request,'login.html',{'form':form})
def home(request,id):
    user=Table1.objects.get(id=id)
    return render(request,'home.html',{'user':user})
def mail(request):
    if request.method =='POST':
        cname=request.POST.get('contact_name')
        print(cname,"ggggggggggggggggggg")
        cemail=request.POST.get('contact_email')
        cmessage=request.POST.get('contact_message')
        toemail="fakerv80@gmail.com"
        res=send_mail(cname,cmessage,settings.EMAIL_HOST_USER,[toemail],fail_silently=False)
        if(res==1):
            msg="Mail sent Successfully"
        else:
            msg="Mail could not be sent"
        return HttpResponse(msg)
    else:
        return render(request,'mail.html')

rvDjango/project8/app8/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    welcome {{user.Name}}
</body>
</html>

rvDjango/project8/app8/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Secure Register
        </title>
    </head>
    <body>
        {%for msg in messages%}
        {{msg}}
        {%endfor%}
        <br>
        To Register your info click Register <br>
        {{datas}}
       
        
        <a href="{% url 'app8:register' %}">Register</a>
        <a href="{% url 'app8:login' %}">Login</a>
        <a href="{% url 'app8:mail' %}">mail</a>
    </body>
</html>

rvDjango/project8/app8/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Document
        </title>
    <body>
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        <form action="" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    {{form.as_table}}
                </tr>
            </table>
            <input type="submit" value="Login">
        </form>
    </body>
    </head>
</html>

rvDjango/project8/app8/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <form action="{% url 'app8:mail' %}" method="post" class="contact-form">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" id="contact_name" name="contact_name" class="form-control" placeholder="Name" required/>
        </div>
        <div class="form-group">
            <input type="text" id="contact_email" name="contact_email" class="form-control" placeholder="Email" required/>
        </div>
        <div class="form-group">
            <textarea id="text" id="contact_message" name="contact_message" class="form-control" rows="'9" placeholder="Message" required></textarea>
        </div>
        <button type="submit" class="float-right tm-button">
            Send
        </button>
    </form>
</body>
</html>

rvDjango/project8/app8/templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Table Registration
        </title>
    </head>
    <body>
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        This is Register Table<br>
        <form action="" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    {{form.as_table}}
                </tr>
            </table>
            <input type="submit" name="btsub" value="Register">
        </form>
    </body>
</html>